version: '3.8'

services:
  # Express Backend (只運行後端)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge